<?php
namespace TwoDot7\Broadcast;
use \TwoDot7\Mailer as Mailer;
use \TwoDot7\Database as Database;
#  _____                      _____ 
# /__   \__      _____       |___  |
#   / /\/\ \ /\ / / _ \         / / 
#  / /    \ V  V / (_) |  _    / /  
#  \/      \_/\_/ \___/  (_)  /_/   

/**
 * Broadcast Origin/Target from/to a User.
 * const USER 1
 * @example Can be accessed by other Namespaces as \TwoDot7\Broadcast\USER or, (int)1.
 */
const USER = 1;

/**
 * Broadcast Origin/Target from/to a registered Bit.
 * const BIT 2
 */
const BIT = 2;

/**
 * Broadcast Origin from the System.
 * const BIT 2
 */
const SYSTEM = 3;

/**
 * Broadcast Origin/Target from/to a Group.
 * const GROUP 4
 */
const GROUP = 4;

/**
 * Broadcast Source to Custom Key.
 * const CUSTOM 5
 */
const CUSTOM = 5;

/**
 * Broadcast Target Default.
 */
const _DEFAULT = 6;

/**
 * Broadcast Visibility Private.
 */
const _PRIVATE = 7;
/**
 * Broadcast Visibility Public.
 */
const _PUBLIC = 8;

/**
 * Action wrapper class for Broadcasts.
 */
class Action {
	public static function Add($Data = array()) {
		// At least the Addition data must be sent in the API call.
		// Fields:
		// OriginType: Required USER / BIT / or SYSTEM
		// Origin: Required. UserName or BitID or System Function, which/who is calling the Addition API
		// TargetType: Optional. USER / Group or Custom.
		// Target: In case of USER: List of UserName(s),
		// Target: In case of Group: List of group(S),
		// Target: In case of Custom: 0.
		// Visible: Default: 0. Public: 1, Target only: 2.
		// Datatype: Index, Generated by the Util::Pack.
		// Data: Packed data.

		if (isset($Data['OriginType'])) switch ($Data['OriginType']) {
			case \TwoDot7\Broadcast\USER:
				if (!isset($Data['Origin']) || !\TwoDot7\Util\Redundant::UserName($Data['Origin']))
					return \TwoDot7\Exception\Error\NotFound::UserName();
				break;

			case \TwoDot7\Broadcast\BIT:
				if (!isset($Data['Origin']) || !\TwoDot7\Util\Redundant::Bit($_Data['Origin']))
					return \TwoDot7\Exception\Error\NotFound::Bit();
				break;

			case \TwoDot7\Broadcast\SYSTEM:
				if (!isset($Data['Origin']) || !\TwoDot7\Validate\Alphanumeric($Data['Origin'], 6, 255)) {
					\TwoDot7\Util\Log("Invalid Broadcast Origin by System: {$Data['Origin']}", "ALERT");
					return \TwoDot7\Exception\Error\Generic();
				}
				break;

			default:
				throw new \TwoDot7\Exception\InvalidArgument("Argument 'OriginType' is not valid.");
		} else throw new \TwoDot7\Exception\IncompleteArgument("OriginType is not specified.");

		if (isset($Data['TargetType'])) switch ($Data['TargetType']) {
				case \TwoDot7\Broadcast\USER:
					if (!isset($Data['Target'])) {
						throw new \TwoDot7\Exception\IncompleteArgument("'Target' is required argument.", 1);
					}
					elseif (is_array($Data['Target'])) {
						;
					} elseif (is_string($Data['Target'])) {
						$Data['Target'] = array($Data['Target']);
					} else {
						throw new \TwoDot7\Exception\InvalidArgument("Argument 'Target' is not valid.");
					}

					foreach ($Data['Target'] as $UserName) {
						if (!\TwoDot7\Util\Redundant::UserName($UserName)) 
							return \TwoDot7\Exception\Error\NotFound::UserName();
					}

					$Data['Target'] = json_encode($Data['Target']);
					break;

				case \TwoDot7\Broadcast\GROUP:
					if (!isset($Data['Target'])) {
						throw new \TwoDot7\Exception\IncompleteArgument("'Target' is required argument.", 1);
					}
					elseif (is_array($Data['Target'])) {
						;
					} elseif (is_string($Data['Target'])) {
						$Data['Target'] = array($Data['Target']);
					} else {
						throw new \TwoDot7\Exception\InvalidArgument("Argument 'Target' is not valid.");
					}

					foreach ($Data['Target'] as $Group) {
						if (!\TwoDot7\Util\Redundant::Group($Group)) 
							return \TwoDot7\Exception\Error\NotFound::Group();
					}

					$Data['Target'] = json_encode($Data['Target']);
					break;

				case \TwoDot7\Broadcast\CUSTOM:
				default:
					if (isset($Data['Target'])) \TwoDot7\Util\Log("WARNING: Target not supported for CUSTOM broadcasts.", "DEBUG");
					$Data['Target'] = json_encode(array());
		} else throw new \TwoDot7\Exception\InvalidArgument("TargetType is not a valid type.");
		
		if (isset($Data['Visible'])) switch ($Data['Visible']) {
			case \TwoDot7\Broadcast\_PRIVATE:
			case \TwoDot7\Broadcast\_PUBLIC:
				break;

			default:
				$Data['Visible'] = \TwoDot7\Broadcast\_PUBLIC;
		} else $Data['Visible'] = \TwoDot7\Broadcast\_PUBLIC;

		// Pack data.
		$Response = Utils::Pack($Data['Data']);
		// Set Datatype and Data.
		$Data['Datatype'] = $Response['Datatype'];
		$Data['Data'] = $Response['Data'];
		$Data['Timestamp'] = time();

		$Query = "INSERT INTO _broadcast (OriginType, Origin, TargetType, Target, Visible, Datatype, Data, Timestamp) VALUES (:OriginType, :Origin, :TargetType, :Target, :Visible, :Datatype, :Data, :Timestamp)";
		
		$Response = \TwoDot7\Database\Handler::Exec($Query, $Data)->rowCount();

		return array( 'Success' => (bool)$Response );
	}

	public static function Remove() {
		// Deletes a broadcast
	}

	public static function Update() {
		// Updates a broadcast
	}

	public static function CreateFeed() {
		// Creates the Feed.
	}
}

class Utils {
	public static function Pack(&$Data) {
		// Packs the Raw broadcast data. Packs images and stuff as well.
		// Only supports the Text Data for now.
		// Data Schema: BroadcastText -> Contains the Text of broadcast. Supports Markdown.
		// 				BroadcastFileAttachements -> Contains various broadcast files. Not Supported yet.
		// 				BroadcastMeta -> Contains various meta.
		return array(
			'Datatype' => 1,
			'Data' => json_encode($Data['BroadcastText'])
			);
	}

	public static function Unpack() {
		// Unpacks a Packed broadcast data.
	}
}