<?php

function atfPutHead() {
	global $PageTitle;
	global $SiteMeta;
	global $Generator;
	global $SEOMeta;
	?>
		<!--
		<?php echo "$Generator"; ?>

		  ______________  ____  _  ______
		 / ___/  _/ ___/ / __ \/ |/ / __/
		/ /___/ // /__  / /_/ /    / _/  
		\___/___/\___/  \____/_/|_/___/  


		>CIC One< Template Library.

		<UICommons.php>
		For documentation, please write to the author.
		For source, please write to the author.

		Authored for CIC One, by Prashant Sinha <prashantsinha@outlook.com>
		-->
		
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

		<title><?php printf("%s | %s | %s", $PageTitle, $SiteMeta['Title'], $SiteMeta['Sub']); ?></title>

		<link rel="shortcut icon" href="assets/images/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon-precomposed" href="/assets/images/apple-touch-icon.png" type="image/png" />

		<meta name="description"	content="<?php echo $SEOMeta['Description']; ?>" />
		<meta name="keywords"		content="<?php echo $SEOMeta['Keywords']; ?>" />
		<meta name="robots"			content="index, follow" />
		<meta name="google"			content="notranslate" />
		<meta name="author"			content="<?php echo $SEOMeta['Author'];?>" />
		<meta name="generator"		content="<?php echo $SEOMeta['Generator'];?>" />

		<meta name="viewport"		content="width=device-width, initial-scale=1, maximum-scale=1" />

		<link rel="stylesheet"		href="assets/css/app.v1.css"	type="text/css" />
		<link rel="stylesheet"		href="assets/css/style.css"		type="text/css" />
		<link rel="stylesheet"		href="assets/css/hacks.php"		type="text/css" />

		<script src="assets/js/jquery.js"></script>

		<!--[if lt IE 9]>	
			<script src="js/ie/html5shiv.js"></script>
			<script src="js/ie/respond.min.js"></script>
			<script src="js/ie/excanvas.js"></script>
		<![endif]-->
	<?php
}

function atfPutFoot($__Arg = "SMALL") {
	global $SiteMeta;
	switch ($__Arg) {
		case	"SMALL":		echo $SiteMeta['FootPretty'];
								break;
	}
}

function atfGetPageTitle($__Mode) {
	switch ($__Mode) {
		case	'DEFAULT'	:	return "Undetermined Page";
		case	'LOGIN'		:	return "Sign In to your account on CIC One";
		case	'REGISTER'	:	return "Sign Up to get an account on CIC One";
		case	'EMVERIFY'	:	return 'Please enter the EMail verification code you recieved on your EMail. <a href="#">Having Trouble?</a>';
		case	'PROFILE'	:	return "Profile";
	}
}

function atfPutMessages($Data) {
	if(gettype($Data)=='array' & isset($Data['Messages'])) { 
		foreach ($Data['Messages'] as $Message) {
			printf ('<div class="%s">',$Message['UIClass']);
			printf 	('<p>%s</p>', $Message['Message']);
			echo '</div>';
		}
	}
	else;
}

function atfPutPageMood($Data) {
	if (isset($Data['Mood'])) {
		echo '<!-- Autogenerated Mood DEXTR -->';
		switch ($Data['Mood']) {
			case	'RED'	:	echo '<div class="Bg-Gen-Hack-Red-Tint" style="display: block; display: initial"></div>';	break;
			case	'BLUE'	:	echo '<div class="Bg-Gen-Hack-Blue-Tint" style="display: block; display: initial"></div>';	break;
			case	'GREEN'	:	echo '<div class="Bg-Gen-Hack-Green-Tint" style="display: block; display: initial"></div>';	break;
			case	'WHITE'	:	echo '<div class="Bg-Gen-Hack-No-Tint" style="display: block; display: initial"></div>';	break;
		}
	}
}

function tShowBar($__Arg) {
	$UserName = fSetCookie('UserName');
	$Login = $UserName === 0 ? false : true;
	$Data = '';
	if (!$Login) {
		$UserName = "Guest";
	}
	try {
		$Meta = new UserMeta($UserName);
		$Data = $Meta->GetData('Mini', FALSE);
	}
	catch (Exception $E) {
		tHttpResponse(403);
	}
	?>
	<aside class="bg-black aside <?php if($__Arg['Collapse']) echo 'spl-header';?>" id="nav">
		<section class="vbox">
			<header class="header header-md navbar navbar-fixed-top-xs bg" style="z-index:9">
				<div class="navbar-header">
					<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav"> <i class="fa fa-bars"></i> 
					</a>
					<a href="index.php" class="navbar-brand">
						<img src="assets/images/logo.png" class="m-r-sm <?php if($__Arg['Collapse']) echo 'spl-logo';?>" >
						<?php if($__Arg['Collapse']) echo '<img src="assets/images/OneLtSm.png" class="spl-logo-alt">';?>
					</a>
					<a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user"> <i class="fa fa-cog"></i> 
					</a>
				</div>
			</header>
			<section class="w-f scrollable">
				<!-- nav -->
				<div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railOpacity="0.2">
					<div class="clearfix wrapper dker nav-user hidden-xs spl-user-info">
						<div class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
								<span class="thumb avatar"> 
									<img src="<?php echo $Data['DPLocation'];?>" class='sm-dp-size-hack'> 
									<i class="<?php echo $Data['Badge']? 'on': 'off'; ?> md b-black"></i> 
								</span>  
								<span class="hidden-nav-xs clear"> 
									<span class="block m-t-xs"> 
										<strong class="font-bold text-lt"><?php echo (strlen($Data['Name']) > 3)?$Data['Name']:'CIC One User';?></strong> <b class="caret"></b> 
									</span> 
									<span class="text-muted text-xs block"><?php echo $Data['Bio'];?></span>
								</span>
							</a>
							<ul class="dropdown-menu">
								<?php if (!$Login) { ?>
									<li> <a href="#">Take a tour</a>
									</li>
									<li> <a href="register.php">Register an Account</a>
									</li>
									<li> <a href="login.php">Login</a>
									</li>
									<li> <a href="#">Help/Support</a> 
									</li>
								<?php }
								else { ?>
									<li> <a href="#">Settings</a> 
									</li>
									<li> <a href="profile.php">Profile</a> 
									</li>
									<li> <a href="#">Help/Support</a> 
									</li>
									<li> <a href="logout.php">Logout</a> 
									</li>
								<?php }?>
							</ul>
						</div>
					</div>
					<!-- nav -->
					<nav class="nav-primary hidden-xs">
						<ul class="nav nav-main" data-ride="collapse">
							<li class="<?php if($__Arg['Page']==='Broadcasts') echo 'active';?>">
								<a href="index.php"> 
									<b class="badge bg-primary pull-right">0</b>
									<i class="fa fa-rss-square"></i> <span class="">Broadcasts</span> 
								</a>
							</li>
							<li class="<?php if($__Arg['Page']==='Bulletin') echo 'active';?>">
								<a href="bulletin.php" class="auto">
									<i class="i i-grid icon"></i> <span class="">Bulletin</span> 
								</a>
							</li>
							<?php if($Login) { ?>
								<li class="<?php if($__Arg['Page']==='Messaging') echo 'active';?>">
									<a href="messaging.php" class="auto">
										<b class="badge bg-success dker pull-right">0</b>
										<i class="i i-chat2 icon"></i> <span class="">Messaging</span> 
									</a>
								</li>
								<li class="<?php if($__Arg['Page']==='Alerts') echo 'active';?>">
									<a href="#" class="auto">
										<b class="badge bg-danger dker pull-right">0</b>
										<i class="fa fa-bell"></i> <span class="">Alerts</span> 
									</a>
								</li>
							<?php } else { ?>
								<li>
									<a href="login.php" class="auto">
										<i class="fa fa-sign-in"></i> <span class="">Login</span> 
									</a>
								</li>
								<li>
									<a href="register.php" class="auto">
										<i class="fa fa-plus-square"></i> <span class="">Create an Account</span> 
									</a>
								</li>
							<?php } ?>
							<li class="<?php if($__Arg['Page']==='People') echo 'active';?>">
								<a href="#" class="auto">
									<i class="fa fa-users"> </i>  <span class="">People</span> 
								</a>
							</li>
							<li>
								<a href="#" class="auto">
									<i class="fa fa-code"> </i>  <span class="">CIC Open Source</span> 
								</a>
							</li>
						</ul>
						<div class="line dk hidden-nav-xs spl-user-info"></div>
						<div class="text-muted text-xs hidden-nav-xs padder m-t-sm m-b-sm spl-user-info">Community</div>
						<ul class="nav spl-user-info">
							<li>
								<a href="#"> <i class="i i-hexagon2 text-success"></i>  <span>Faculty</span> 
								</a>
							</li>
							<li>
								<a href="#"> <i class="i i-circle-sm text-primary"></i>  <span>Students</span> 
								</a>
							</li>
						</ul>
					</nav>
					<!-- / nav -->

				</div>
				<!-- / nav -->
			</section>
			<footer class="footer hidden-xs footer-show-hack text-center-nav-xs dker">
				
			</footer>
		</section>
	</aside>
	<?php
}

?>